version: "3"

services:
  web:
    build: "./web"
    ports:
      - "5000:5000"
    tty: true
    links:
      - my_db
  redis:
    image: "redis:alpine"
  my_db:
    build: "./db"
    # image: mongo:4.2.6